export const actionTypes = { 
    FETCH_NEWS: 'FETCH_NEWS',
    FETCH_LATEST_NEWS: 'FETCH_LATEST_NEWS',
    REMOVE_ALL_NEWS:'REMOVE_ALL_NEWS',
    SET_NEWS_ID: 'SET_NEWS_ID',
    SET_LATESTNEWS_ID: 'SET_LATESTNEWS_ID',


    SET_API_VALUE: 'SET_API_VALUE',
    SET_API_VALUE_SEARCH: 'SET_API_VALUE_SEARCH',
    SET_COUNTRY_VALUE: 'SET_COUNTRY_VALUE',
    SET_CATEGORY_VALUE: 'SET_CATEGORY_VALUE',
    SET_SEARCH_VALUE: 'SET_SEARCH_VALUE',
}